#!/usr/bin/env python3
from __future__ import annotations

import itertools
import json
import sys
from collections import deque
from pathlib import Path

ROOT=Path(__file__).parent
DATA=ROOT/"content.json"
errors=[]

def fail(msg:str)->None:
    errors.append(msg)

try:
    data=json.loads(DATA.read_text(encoding="utf-8"))
except Exception as exc:
    print(f"ACT6 VALIDATION FAILED: cannot load content.json: {exc}")
    sys.exit(1)

if data.get("act")!=6:
    fail("act must be 6")
if data.get("status")!="staging-unlinked":
    fail("Act 6 staging must remain unlinked")
if data.get("runtime_connected") is not False:
    fail("Act 6 must not connect to earlier runtimes before Human Gate")

graph=data.get("candidate_graph",{})
slots=graph.get("slots",[])
landmarks=graph.get("landmarks",[])
edges=[tuple(x) for x in graph.get("edges",[])]
main_route=graph.get("main_route",[])
canonical=graph.get("canonical_assignment",{})

if len(slots)!=6 or len(set(slots))!=6:
    fail("candidate graph must have six unique slots")
if len(landmarks)!=6 or len(set(landmarks))!=6:
    fail("candidate graph must have six unique landmark cards")
if set(canonical.keys())!=set(landmarks) or set(canonical.values())!=set(slots):
    fail("canonical assignment must be a bijection")

adj={s:set() for s in slots}
for a,b in edges:
    if a not in adj or b not in adj:
        fail(f"edge references unknown slot: {a}-{b}")
        continue
    adj[a].add(b);adj[b].add(a)

def distance(a:str,b:str)->int|None:
    q=deque([(a,0)])
    seen={a}
    while q:
        node,d=q.popleft()
        if node==b:
            return d
        for nxt in adj.get(node,()):
            if nxt not in seen:
                seen.add(nxt);q.append((nxt,d+1))
    return None

constraints=data.get("constraints",{})
chain=constraints.get("act4_chain",{}).get("ordered_landmarks",[])
distance_table=constraints.get("distance_table",[])

solutions=[]
for perm in itertools.permutations(slots):
    assignment=dict(zip(landmarks,perm))

    # Act 4 chain must occupy four consecutive positions on the normalized
    # main route. Orientation is intentionally unknown until all constraints
    # are applied.
    try:
        idx=[main_route.index(assignment[x]) for x in chain]
    except ValueError:
        continue
    diffs=[idx[i+1]-idx[i] for i in range(len(idx)-1)]
    if not (all(x==1 for x in diffs) or all(x==-1 for x in diffs)):
        continue

    ok=True
    for row in distance_table:
        if distance(assignment[row["a"]],assignment[row["b"]])!=row["distance"]:
            ok=False;break
    if ok:
        solutions.append(assignment)

required_count=constraints.get("solution_count_required")
if len(solutions)!=required_count:
    fail(f"constraint system solution count must be {required_count}; got {len(solutions)}")
if len(solutions)==1 and solutions[0]!=canonical:
    fail(f"unique solution does not match canonical assignment: {solutions[0]}")

# Named route must be generated from the solved main-route assignment, not
# copied from a complete source map.
named=graph.get("named_route",{})
if named.get("name")!="水無坂":
    fail("named route must be 水無坂")
if named.get("slots")!=main_route:
    fail("水無坂 route must use solved five-slot main route")
if named.get("generated_by_synthesis") is not True:
    fail("route name placement must be marked generated by synthesis")

supports=data.get("supports",{})
minimums=data.get("support_minimums",{})
for landmark,min_count in minimums.items():
    groups=supports.get(landmark,[])
    if len(set(groups))<min_count:
        fail(f"{landmark} has fewer than {min_count} independent support groups")

artifact=data.get("generated_artifact",{})
if artifact.get("id")!="EV-032":
    fail("generated artifact must be EV-032")
if artifact.get("artifact_type")!="generated synthesis":
    fail("EV-032 must be explicitly generated synthesis")
if artifact.get("complete_source_map_found") is not False:
    fail("no complete source map may be found")
if artifact.get("generated_during_investigation") is not True:
    fail("EV-032 must be generated during current investigation")
required_copy="\n".join(artifact.get("required_copy",[]))
for phrase in (
    "この完成図と同一の資料は、現在確認されている1998年資料には存在しません。",
    "各資料に分散していた位置関係を統合して作成したものです。",
):
    if phrase not in required_copy:
        fail(f"EV-032 missing generated-vs-found copy: {phrase}")

placements=artifact.get("placements",{})
if set(placements.keys())!=set(slots):
    fail("EV-032 must record provenance for every slot")
for slot,item in placements.items():
    if item.get("landmark") not in landmarks:
        fail(f"{slot} has unknown landmark provenance")
    if len(item.get("sources",[]))<2:
        fail(f"{slot} must retain at least two placement sources")

state=data.get("state_machine",{})
expected_transitions=[
    ("MAP_INCOMPLETE","PZ011_SOLVED","MAP_COMPLETE_UNOBSERVED"),
    ("MAP_COMPLETE_UNOBSERVED","VISIT_SITE007_OR_SITE00108","REALITY_CHANGE_OBSERVED"),
    ("REALITY_CHANGE_OBSERVED","VISIT_BOTH_REALITY_ANCHORS","PZ012_OBSERVED"),
    ("PZ012_OBSERVED","ACKNOWLEDGE_RECONSTRUCTION_HAZARD","ENDING_AVAILABLE"),
]
actual=[(x.get("from"),x.get("event"),x.get("to")) for x in state.get("transitions",[])]
if actual!=expected_transitions:
    fail("state-machine transition order mismatch")
if state.get("ending_available_only_after")!="PZ012_OBSERVED":
    fail("ending availability must be gated by PZ012 observation")
first=state.get("transitions",[{}])[0]
if first.get("side_effect")!="REALITY_B_ACTIVE":
    fail("PZ-011 solve must activate reality state B without popup")

fixtures=data.get("fixtures",{})
s7=fixtures.get("site007",{})
shared7=s7.get("shared",{})
a7=s7.get("state_a",{})
b7=s7.get("state_b",{})
if s7.get("path")!="/bousai-now/areas/":
    fail("SITE-007 path mismatch")
if shared7.get("last_updated")!="2026-04-01":
    fail("SITE-007 A/B must share fixed ordinary update date")
if a7.get("rows")!=[1,2,3,4,5,6,7]:
    fail("SITE-007 state A must contain 1-7")
if b7.get("rows")!=[1,2,3,4,5,6,7,8]:
    fail("SITE-007 state B must contain 1-8")
if b7.get("legend")!=[1,2,3,4,5,6,7,8]:
    fail("SITE-007 state B legend must contain 1-8")
if b7.get("area8",{}).get("name")!="第8避難区":
    fail("SITE-007 state B area8 row missing")

s1=fixtures.get("site001_08",{})
if s1.get("path")!="/old-bousai/disaster/areas/08/":
    fail("SITE-001 /08 path mismatch")
if s1.get("state_a",{}).get("resolves") is not False:
    fail("SITE-001 /08 state A must remain missing")
if s1.get("state_b",{}).get("resolves") is not True:
    fail("SITE-001 /08 state B must resolve")
if s1.get("state_b",{}).get("update_date")!="平成15年4月1日":
    fail("SITE-001 /08 state B must use period-appropriate old date")
if s1.get("state_b",{}).get("designated_site")!="旧八号集会所":
    fail("SITE-001 /08 state B designated site mismatch")

pz12=data.get("pz012",{})
if set(pz12.get("required_reality_anchors",[]))!={"SITE-007","SITE-001/08"}:
    fail("PZ-012 must require both reality anchors for full confirmation")
if pz12.get("popup_allowed") is not False:
    fail("PZ-012 state change must not use popup")

gate=data.get("ending_gate",{})
if gate.get("required_state")!="PZ012_OBSERVED":
    fail("ending screen must remain gated after PZ-012")
choices=gate.get("choices",[])
if [x.get("id") for x in choices]!=["END-A","END-B","END-C"]:
    fail("ending choice IDs mismatch")

endings=data.get("endings",{})
if set(endings.keys())!={"END-A","END-B","END-C"}:
    fail("exactly three endings required")
a=endings.get("END-A",{})
b=endings.get("END-B",{})
c=endings.get("END-C",{})
if a.get("site007")!="B" or a.get("site001_08")!="B":
    fail("END-A must retain reality state B")
for x,name in ((b,"END-B"),(c,"END-C")):
    if x.get("site007")!="A" or x.get("site001_08")!="A":
        fail(f"{name} must settle reality anchors to state A")
if b==c:
    fail("END-B and END-C must be mechanically distinct")
if b.get("people")!="mostly_redacted" or b.get("incident")!="minimal":
    fail("END-B must damage person/context preservation")
if c.get("people")!="preserved" or c.get("incident")!="preserved":
    fail("END-C must preserve people and incident chronology")
if c.get("complete_geography")!="suppressed_or_destroyed":
    fail("END-C must suppress precise geography")
if c.get("final_line")!="忘れないために、思い出してはいけないことがある。":
    fail("END-C final line mismatch")

# Ensure action wording does not contain moral labels.
choice_blob=json.dumps(choices,ensure_ascii=False)
for forbidden in data.get("player_facing_forbidden_labels",[]):
    if forbidden in choice_blob:
        fail(f"ending choice contains authorial moral label: {forbidden}")

# No-glitch contract is checked against player-facing fixture/choice/copy data.
player_blob=json.dumps({
    "fixtures":fixtures,
    "pz012":pz12,
    "ending_gate":gate,
    "endings":endings,
    "artifact_copy":artifact.get("required_copy",[]),
},ensure_ascii=False).lower()
for token in data.get("no_glitch_forbidden",[]):
    if token.lower() in player_blob:
        fail(f"Act 6 player-facing contract contains forbidden no-glitch token: {token}")

human=data.get("human_gate",{})
if human.get("issue")!=8 or human.get("required_before_runtime_integration") is not True:
    fail("Human Blind Playtest #8 must remain runtime-integration gate")

print(f"Assignments enumerated: {len(list(itertools.permutations(slots)))}")
print(f"Constraint solutions: {len(solutions)}")
print("Unique geography: enforced")
print(f"Placement provenance slots: {len(placements)}")
print("Support minimums: enforced")
print("Reality fixtures: A/B structural contract enabled")
print("No-glitch state change: enforced")
print("Ending gate: after PZ-012")
print("Ending mechanical distinction: A / B / C")
print("Human-gate isolation: enabled")

if errors:
    print("\nACT6 VALIDATION FAILED")
    for err in errors:
        print(" -",err)
    sys.exit(1)

print("ACT6 VALIDATION PASSED")
